name: Maven Test
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_RANDOM_ROOT_PASSWORD: yes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        run: mvn -B test
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
          MYSQL_USERNAME: test
          MYSQL_PASSWORD: test